/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionPlctu.h"

bool_t
xdr_datos_plctu (XDR *xdrs, datos_plctu *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id_plctu, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->propietario, MAXCAD,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->direccion, MAXCAD,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->consumo))
		 return FALSE;
	return TRUE;
}
