/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionPlctu.h"
#include "gestionSaa.h"

bool_t *
registrar_plctu_1_svc(datos_plctu *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

datos_plctu *
consultar_plctu_1_svc(int *argp, struct svc_req *rqstp)
{
	static datos_plctu  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void
gestion_saa_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	int  notificarplcmms_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_saa, gestion_saa_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = notificarplcmms_1(&notificarplcmms_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}