package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* domingo 2 de junio de 2024 08:21:24 PM COT
*/

public interface GestionDispositivosOperations 
{
  void notificacionmms (grsaa.sop_corba.GestionDispositivosPackage.notificacionDTO objNotificacion);
  int lectura (grsaa.sop_corba.GestionDispositivosPackage.Lectura_DTO objLectura);
  double recuperarFactura (String IdTu, grsaa.sop_corba.GestionDispositivosPackage.Factura_DTOHolder objFactura);
} // interface GestionDispositivosOperations
