package plc_tu.sop_corba;


/**
* plc_tu/sop_corba/GestionAlertas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesalertas.idl
* domingo 2 de junio de 2024 08:21:24 PM COT
*/

public interface GestionAlertas extends GestionAlertasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionAlertas
