package plc_mms.sop_corba;


/**
* plc_mms/sop_corba/GestionPlcTuOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* domingo 2 de junio de 2024 08:21:24 PM COT
*/

public interface GestionPlcTuOperations 
{
  boolean registrar_plctu (plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTO dplctu);
  boolean consultarplctu (int plctuid, plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTOHolder objTU);
  void registrarCallback (plc_tu.sop_corba.GestionAlertas objAlertas);
  void usuariosConectados (plc_tu.sop_corba.GestionAlertas objUsuario);
  boolean recuperarLista (plc_mms.sop_corba.GestionPlcTuPackage.ListaDtoHolder objLista);
  plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO recuperarFactura (String IdTu);
  void notificarFacturas (String IdTu);
  void actualizarLista (plc_mms.sop_corba.GestionPlcTuPackage.ListaDto prmListaTU);
  boolean eliminarTU (String idTu);
} // interface GestionPlcTuOperations
