package plc_tu.sop_corba;


/**
* sop_corba/GestionAlertasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesNotificaciones.idl
* lunes 27 de mayo de 2024 02:28:11 PM COT
*/

public interface GestionAlertasOperations 
{
  void notificar (String usuario, String id, int modo);
} // interface GestionAlertasOperations
