package grsaa.sop_corba.GestionDispositivosPackage;


/**
* grsaa/sop_corba/GestionDispositivosPackage/Factura_DTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* domingo 2 de junio de 2024 08:21:24 PM COT
*/

public final class Factura_DTO implements org.omg.CORBA.portable.IDLEntity
{
  public String id_plctu = null;
  public String lecturaIni = null;
  public String lecturaFin = null;
  public int consumo = (int)0;

  public Factura_DTO ()
  {
  } // ctor

  public Factura_DTO (String _id_plctu, String _lecturaIni, String _lecturaFin, int _consumo)
  {
    id_plctu = _id_plctu;
    lecturaIni = _lecturaIni;
    lecturaFin = _lecturaFin;
    consumo = _consumo;
  } // ctor

} // class Factura_DTO
